apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/tasker-pod/
patchesStrategicMerge:
- ./tasker-patch.yaml
images:
- name: tasker-image
  newName: jnkroeker/tasker-amd64
  newTag: 0.1.13
