apiVersion: v1 
kind: Namespace
metadata:
  name: khyme-system 
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: worker-pod # base Pod name
  namespace: khyme-system 
spec:
  selector:
    matchLabels:
      app: worker 
  template:
    metadata:
      labels:
        app: worker # Selector for Pod name search.
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      hostNetwork: true 
      terminationGracePeriodSeconds: 60
      containers:
        # worker-api container configuration
      - name: worker-api
        # gets patched to the specific docker image name in cluster/worker-pod/kustomization.yaml
        # done to avoid hardcoding image name and version
        image: worker-image
        imagePullPolicy: IfNotPresent
        # define ports to expose;
        # service definition 'worker-service', below, actually exposes these ports
        ports:
        - name: worker-api 
          containerPort: 3000 
        - name: worker-debug 
          containerPort: 4000
---
apiVersion: v1 
kind: Service 
metadata:
  name: worker-service 
  namespace: khyme-system
spec:
  type: ClusterIP
  selector:
    app: worker 
  ports:
  - name: worker-api 
    port: 3000
    targetPort: worker-api 
  - name: worker-debug 
    port: 4000 
    targetPort: worker-debug 
        