apiVersion: v1 
kind: Namespace
metadata:
  name: khyme-system 
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: tasker-pod # base Pod name
  namespace: khyme-system 
spec:
  selector:
    matchLabels:
      app: tasker 
  template:
    metadata:
      labels:
        app: tasker # Selector for Pod name search.
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      hostNetwork: true 
      terminationGracePeriodSeconds: 60
      containers:
        # tasker-api container configuration
      - name: tasker-api
        # gets patched to the specific docker image name in cluster/tasker-pod/kustomization.yaml
        # done to avoid hardcoding image name and version
        image: tasker-image
        imagePullPolicy: IfNotPresent
        # define ports to expose;
        # service definition 'tasker-service', below, actually exposes these ports
        ports:
        - name: tasker-api 
          containerPort: 3000 
        - name: tasker-debug 
          containerPort: 4000
---
apiVersion: v1 
kind: Service 
metadata:
  name: tasker-service 
  namespace: khyme-system
spec:
  type: ClusterIP
  selector:
    app: tasker 
  ports:
  - name: tasker-api 
    port: 3000
    targetPort: tasker-api 
  - name: tasker-debug 
    port: 4000 
    targetPort: tasker-debug 
        