apiVersion: v1 
kind: Namespace
metadata:
  name: khyme-system 
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: tasker-pod # base Pod name
  namespace: khyme-system 
spec:
  selector:
    matchLabels:
      app: tasker 
  template:
    metadata:
      labels:
        app: tasker # Selector for Pod name search.
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      hostNetwork: true 
      terminationGracePeriodSeconds: 60
      containers:
        # tasker-api container configuration
      - name: tasker-api
        # gets patched to the specific docker image name in cluster/tasker-pod/kustomization.yaml
        # done to avoid hardcoding image name and version
        image: tasker-image
        imagePullPolicy: IfNotPresent
        # define ports to expose;
        # service definition 'tasker-service', below, actually exposes these ports
        ports:
        - name: tasker-api 
          containerPort: 3000 
        - name: tasker-debug 
          containerPort: 4000
        readinessProbe: # readiness probes mark the service as available for traffic
          httpGet:
            path: /debug/readiness
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted)
          httpGet:
            path: /debug/liveness 
            port: 4000 
          initialDelaySeconds: 30
          periodSeconds: 30 
          timeoutSeconds: 5 
          successThreshold: 1
          failureThreshold: 2
        env:
          - name: KUBERNETES_NAMESPACE 
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NODENAME 
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: v1 
kind: Service 
metadata:
  name: tasker-service 
  namespace: khyme-system
spec:
  type: ClusterIP
  selector:
    app: tasker 
  ports:
  - name: tasker-api 
    port: 3000
    targetPort: tasker-api 
  - name: tasker-debug 
    port: 4000 
    targetPort: tasker-debug
        