apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/worker-pod/
patchesStrategicMerge:
- ./worker-patch.yaml
images:
- name: worker-image
  newName: jnkroeker/worker-amd64
  newTag: 0.1.2
