apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: worker-pod 
  namespace: khyme-system 
spec:
  replicas: 1 
  strategy:
    type: Recreate 
  selector: 
    matchLabels: 
      app: worker
  template:
    metadata:
      labels: 
        app: worker 
    spec:
      containers:
      - name: worker-api 
      # worker container configuration
        resources: 
          limits:
            cpu: "2000m" # Up to 2 full cores
          requests:
            cpu: "1000m" # Use 1 full core